import {
  BiCheckCircle,
  BiChevronLeft,
  BiChevronRight,
  BiDownload,
  BiPlus,
  BiSolidError,
  BiXCircle,
} from "react-icons/bi";
import { CgBulb, CgFlagAlt } from "react-icons/cg";
import {
  FaCheck,
  FaCheckCircle,
  FaCloudDownloadAlt,
  FaEye,
  FaEyeSlash,
  FaRegCheckSquare,
  FaRegHeart,
  FaRegWindowClose,
} from "react-icons/fa";

import {
  FaCircleCheck,
  FaCircleDollarToSlot,
  FaPlus,
  FaRegCirclePlay,
  FaRegFileImage,
  FaRegFilePdf,
  FaRegImage,
  FaRegStar,
  FaStar,
} from "react-icons/fa6";
import { GoArrowLeft } from "react-icons/go";
import {
  IoIosArrowUp,
  IoIosCamera,
  IoIosCloseCircle,
  IoIosCloseCircleOutline,
  IoIosNotifications,
  IoIosNotificationsOutline,
  IoMdCheckmark,
  IoMdCheckmarkCircleOutline,
  IoMdSend,
} from "react-icons/io";

import {
  IoArrowBackSharp,
  IoBulbSharp,
  IoChevronDown,
  IoChevronForward,
  IoChevronUp,
  IoClose,
  IoDocument,
  IoDocumentOutline,
  IoMenu,
  IoNavigate,
  IoSearch,
  IoSwapVertical,
  IoEyeOutline,
} from "react-icons/io5";

import { HiArrowUturnLeft } from "react-icons/hi2";
import { LuCircleMinus } from "react-icons/lu";
import { MdOutlineEdit } from "react-icons/md";
import {
  PiFadersHorizontalFill,
  PiWarningCircleLight,
  PiWarningDiamondFill,
} from "react-icons/pi";
import { RiDeleteBin6Line, RiExchangeFill } from "react-icons/ri";

export {
  BiCheckCircle,
  BiChevronLeft,
  BiChevronRight,
  BiDownload,
  BiPlus,
  BiSolidError,
  BiXCircle,
  CgBulb,
  CgFlagAlt,
  FaCheck,
  FaCheckCircle,
  FaCircleCheck,
  FaCircleDollarToSlot,
  FaCloudDownloadAlt,
  FaEye,
  FaEyeSlash,
  FaPlus,
  FaRegCheckSquare,
  FaRegCirclePlay,
  FaRegFileImage,
  FaRegFilePdf,
  FaRegHeart,
  FaRegImage,
  FaRegStar,
  FaRegWindowClose,
  FaStar,
  GoArrowLeft,
  HiArrowUturnLeft,
  IoArrowBackSharp,
  IoBulbSharp,
  IoEyeOutline,
  IoChevronDown,
  IoChevronForward,
  IoChevronUp,
  IoClose,
  IoDocument,
  IoDocumentOutline,
  IoIosArrowUp,
  IoIosCamera,
  IoIosCloseCircle,
  IoIosCloseCircleOutline,
  IoIosNotifications,
  IoIosNotificationsOutline,
  IoMdCheckmark,
  IoMdCheckmarkCircleOutline,
  IoMdSend,
  IoMenu,
  IoNavigate,
  IoSearch,
  IoSwapVertical,
  LuCircleMinus as LuMinusCircle,
  MdOutlineEdit,
  PiFadersHorizontalFill,
  PiWarningCircleLight,
  PiWarningDiamondFill,
  RiDeleteBin6Line,
  RiExchangeFill,
};
